function Hd = Filter_IIR
%FILTER_IIR Returns a discrete-time filter object.
% 通带或阻带的截止频率与采样率的选取范围是不能超过采样率的一半
% MATLAB Code
% Generated by MATLAB(R) 8.6 and the Signal Processing Toolbox 7.1.
% Generated on: 07-Sep-2020 10:40:20

% Equiripple FIR Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 48000;  % Sampling Frequency

Fpass = 9600;            % Passband Frequency
Fstop = 12000;           % Stopband Frequency
Dpass = 0.057501127785;  % Passband Ripple-passband ripple
%通频带bai波du动；带内增益平坦度；通带波纹
%通频带用于衡量zhi放大dao电路对不同频率信号的
% 放大能力。由于放大电路中电容、电感及半导体器件结电容等电抗元件的存在，在输入信号频率较低或较高时，放大倍数的数值会下降并产生相移。通常情况下，放大电路只适用于放大某一个特定频率范围内的信号
Dstop = 0.0001;          % Stopband Attenuation-阻带衰减
dens  = 16;              % Density Factor-FIR Equiripple滤波器具有“密度因子”选项，可控制频率网格的密度。增加该值将创建一个滤波器，该滤波器更接近理想的等波纹滤波器，但是随着计算的增加，需要更多的时间。将此值保留为20。

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
